---
version: '3'


tasks:
    up:
    # Creates infrastructure
        dir: ./infra/bootstrap
        dotenv: [../.env]
        cmds:
            - terraform init
            - terraform apply -auto-approve
            - ssh root@172.16.100.30 cat /etc/named.conf | grep secret | grep -o '".*"' | sed s/\"//g > /tmp/tsig-key
            - task: kubernetes
            - task: regenerate_kubeconfig

    kubernetes:
        dir: ./infra/kubernetes
        dotenv: [../.env]
        cmds:
            - terraform init
            - terraform apply -auto-approve

    regenerate_kubeconfig:
        dir: ./infra
        dotenv: [.env]
        cmds:
            - mkdir -p ~/.kube
            - ssh -o 'StrictHostKeyChecking no' -o UserKnownHostsFile=/dev/null root@k3s-master.private.hnatekmar.xyz cat /etc/rancher/k3s/k3s.yaml | sed "s/https:\/\/127.0.0.1:6443/https:\/\/k3s-master.private.hnatekmar.xyz:6443/g" > ~/.kube/config

    setup_flux:
        dir: ./infra
        dotenv: [.env]
        cmds:
            - flux bootstrap github --owner=${GITHUB_USER} --repository=${GITHUB_REPO} --branch=main --path=./clusters/${CLUSTER_NAME} --personal

    down:
    # Destroys infrastructure
        dir: ./infra/bootstrap
        dotenv: [../.env]
        cmds:
            - task: down_kubernetes
            - terraform destroy -auto-approve

    down_kubernetes:
        # Destroys infrastructure
        dir: ./infra/kubernetes
        dotenv: [../.env]
        cmds:
            - terraform destroy -auto-approve
