---
- hosts: all
  tasks:
    - name: Include user_env
      include_tasks: ../../common/user_env.yaml

    - name: Include nfs
      include_tasks: ../../common/nfs.yaml

    - name: Install packages
      yum:
        name:
          - rsync
          - socat
        state: present

    - name: Install k3s worker
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://k3s-master.private.hnatekmar.xyz:6443 K3S_TOKEN='k3s-testing' sh -